import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/layout/header/Header";
import Sidebar from "@/components/layout/sidebar/Hidebar";
import ThemeProvider from "@/app/theme-provider";

export const metadata: Metadata = {
  title: "Crm Playground",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets:['latin'],
  display:'swap'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <Sidebar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
