import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header/header";
import Sidebar from "@/components/layout/sidebar/sidebar";
import ThemeProvider from "@/components/theme-provider";


export const metadata: Metadata = {
  title: "Crm Playground",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
          <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet" />
        </style>
      </head>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
        >
          <Header />
          <Sidebar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
